repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.4.1'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-merge-conflict
    - id: mixed-line-ending
  #- repo: https://github.com/pycqa/bandit
  #  rev: 1.7.4
  #  hooks:
  #  - id: bandit
  #    exclude: tests/
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    - id: python-safety-dependencies-check
      files: dashboards/app/requirements.txt
